name: fronend
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  image_picker: ^0.6.3+4
  geolocator: ^5.3.0
  google_maps_flutter: ^0.5.24+1
  fluttertoast: ^3.1.3
  dio: ^3.0.9
  path: ^1.6.4
  cupertino_icons: ^0.1.2
  convert: ^2.1.1
  crypto: ^2.1.3
  keyboard_avoider: ^0.1.2
  flutter_secure_storage: ^3.3.1+1
  firebase_storage: ^2.1.0+1
  font_awesome_flutter: ^8.2.0
  custom_switch_button: ^0.5.0
  smooth_star_rating: 1.0.4+2
  google_nav_bar: ^2.0.0
  line_icons: ^0.2.0
  dependencies:
  carousel_slider: ^1.3.0
  flutter_map:
  liquid_pull_to_refresh: ^1.1.0
  flutter_rating_bar: ^3.0.1+1
  location: ^3.0.2
  connectivity: '>=0.4.8+6 <2.0.0'
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
